#language: node_js

#node_js:
#  - 'LTS'

cache:
  directories:
    - node_modules

before_install:
  # install nodejs and npm manually
  - curl -sL https://deb.nodesource.com/setup_12.x -o nodesource_setup.sh
  - sudo bash nodesource_setup.sh
  - sudo apt-get install -y nodejs
  - source ~/.bashrc
  - node --version
  - npm --version
  # copy .env file
  - cp .env.sample .env
  - cat .env

install:
  - npm install

script:
  - npm run test
  - npm run build
