language: node_js

node_js:
  - '12.13.0'

cache:
  directories:
    - node_modules

before_install:
  # install nodejs and npm manually
#  - curl -sL https://deb.nodesource.com/setup_12.x -o nodesource_setup.sh
#  - sudo bash nodesource_setup.sh
#  - sudo apt install -y nodejs
#  - source ~/.bashrc
  - node --version
  - npm --version

install:
  - npm install

before_script:
  # copy .env file
  - cp .env.sample .env
  - cat .env

script:
  - npm run test
  - npm run build
