language: node_js

node_js:
  - '12.13.0'

cache:
  directories:
    - node_modules

before_install:
  - node --version
  - npm --version

install:
  - npm install

before_script:
  # copy .env file
  - cp .env.sample .env
  - cat .env

script:
  - npm run lint
  - npm run test
  - npm run build
